repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--only-sections"]
        exclude: "alembic/versions/|tests/|alembic/migrations|easter_eggs/|.venv/|.vscode/|__pycache__/"

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        exclude: "alembic/versions/|tests/|alembic/migrations|easter_eggs/|.venv/|.vscode/|__pycache__/"

  # Эти два плагина для pre-commit будут временно отключены, т.к. они не могут работать с exclude-папками, именно в пределах pre-commit.
  # - repo: https://github.com/pre-commit/mirrors-pylint
  #   rev: v3.0.0a5
  #   hooks:
  #     - id: pylint
  #       args:
  #         ["--disable=C0114,C0115,C0116,R0903,W0511", "--max-line-length=100"]
  #       exclude: "alembic/|alembic/versions/|tests/|alembic/migrations|easter_eggs/|.venv/|.vscode/|__pycache__/"
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.11.2
  #   hooks:
  #     - id: mypy
  #       args:
  #         [
  #           "--ignore-missing-imports",
  #           "--exclude",
  #           "alembic/|alembic/versions/|tests/|alembic/migrations|easter_eggs/|.venv/|.vscode/|__pycache__/",
  #         ]
