version: "3.7"

services:
  e-love-fe-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-love-frontend-api
    ports:
      - "8001:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: e-love-mysql
    env_file:
      - ./docker/db-app/db.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:
