version: "3.7"

services:
  e-love-fe-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-love-frontend-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
      ]
