"""uc-37-add-supabase-field-usr-table

Revision ID: 351afa802ae4
Revises: ffdccf47792f
Create Date: 2024-12-25 21:44:58.142032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351afa802ae4'
down_revision: Union[str, None] = 'ffdccf47792f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('supabase_user_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'user', ['supabase_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'supabase_user_id')
    # ### end Alembic commands ###
