"""uc-11-add-posts-categories-model-and-corrections

Revision ID: 5983095292a3
Revises: e6a9bc23436c
Create Date: 2024-09-26 19:23:16.023304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5983095292a3'
down_revision: Union[str, None] = 'e6a9bc23436c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_categories',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['user_post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    op.drop_constraint('user_post_ibfk_1', 'user_post', type_='foreignkey')
    op.drop_column('user_post', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_post', sa.Column('category_id', mysql.VARCHAR(length=36), nullable=False))
    op.create_foreign_key('user_post_ibfk_1', 'user_post', 'categories', ['category_id'], ['id'])
    op.drop_table('posts_categories')
    # ### end Alembic commands ###
