"""uc-11-add-unique-attrs-constraints

Revision ID: 942629789895
Revises: 67577aefe0a2
Create Date: 2024-11-25 13:10:09.115871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942629789895'
down_revision: Union[str, None] = '67577aefe0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'categories', ['category_name'])
    op.create_unique_constraint(None, 'user_gender', ['gender_name'])
    op.create_unique_constraint(None, 'user_status', ['status_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_status', type_='unique')
    op.drop_constraint(None, 'user_gender', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    # ### end Alembic commands ###
