"""UC-34: upgrade user_images table

Revision ID: 94d192a96409
Revises: 942629789895
Create Date: 2024-12-08 16:32:57.445663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '94d192a96409'
down_revision: Union[str, None] = '942629789895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('img_url', sa.String(length=124), nullable=False))
    op.drop_column('user_images', 'decoded_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('decoded_img', mysql.VARCHAR(length=124), nullable=False))
    op.drop_column('user_images', 'img_url')
    # ### end Alembic commands ###
