"""uc_34_update_user_imgs_table

Revision ID: b2d3f56acb1c
Revises: 942629789895
Create Date: 2024-12-12 18:26:44.569722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b2d3f56acb1c'
down_revision: Union[str, None] = '942629789895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('img_url', sa.String(length=240), nullable=False))
    op.drop_column('user_images', 'decoded_img')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_images', sa.Column('decoded_img', mysql.VARCHAR(length=124), nullable=False))
    op.drop_column('user_images', 'img_url')
    # ### end Alembic commands ###
