"""impr-uc-12-Update-current-db-models

Revision ID: e6a9bc23436c
Revises: 0b6fc3c8d79c
Create Date: 2024-09-24 20:22:26.389138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6a9bc23436c'
down_revision: Union[str, None] = '0b6fc3c8d79c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_categories',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.create_table('user_genders',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gender_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['gender_id'], ['user_gender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'gender_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['user_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.drop_constraint('user_ibfk_3', 'user', type_='foreignkey')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'gender_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender_id', mysql.VARCHAR(length=36), nullable=False))
    op.add_column('user', sa.Column('role_id', mysql.VARCHAR(length=36), nullable=False))
    op.create_foreign_key('user_ibfk_1', 'user', 'user_gender', ['gender_id'], ['id'])
    op.create_foreign_key('user_ibfk_3', 'user', 'user_role', ['role_id'], ['id'])
    op.drop_table('user_roles')
    op.drop_table('user_genders')
    op.drop_table('user_categories')
    # ### end Alembic commands ###
