"""uc-37-update-user-table-supabase

Revision ID: ffdccf47792f
Revises: b2d3f56acb1c
Create Date: 2024-12-25 21:35:53.257353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ffdccf47792f'
down_revision: Union[str, None] = 'b2d3f56acb1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
