services:
  db:
    image: mysql:8.0
    container_name: e-love-db
    env_file:
      - ./docker/db-app/db.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 10s
      timeout: 5s
      retries: 5

  e-love-fe-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fe-api
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
    driver: local
