name: CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Запуск при создании релиза или тэга
  release:
    types: [created]

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: myapp:latest
