name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: e-love-frontend-api-db
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: e-love-frontend-api
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_ENV_PATH: docker/app.env

      - name: Check code formatting with black
        working-directory: e-love-frontend-api
        run: |
          poetry run black --check .

      - name: Check import sorting with isort
        working-directory: e-love-frontend-api
        run: |
          poetry run isort --check-only .

      # - name: Lint code with flake8
      #   working-directory: e-love-frontend-api
      #   run: |
      #     poetry run flake8 .

      # - name: Type checking with mypy
      #   working-directory: e-love-frontend-api
      #   run: |
      #     poetry run mypy .

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: e-love-frontend-api
          file: e-love-frontend-api/Dockerfile
          push: false
          tags: myapp:latest

      - name: Run Docker container
        run: |
          docker run -d \
            --name fe-api-container \
            -p 8080:8000 \
            --env DATABASE_URL=${{ secrets.DATABASE_URL }} \
            myapp:latest

      - name: Wait for the app to be ready
        run: |
          for i in {1..10}; do
            if curl -f http://localhost:8080/; then
              echo "App is ready!"
              exit 0
            else
              echo "Waiting for the app to be ready..."
              sleep 6
            fi
          done
          echo "App did not become ready in time."
          exit 1

      - name: Test application response
        run: |
          curl -f http://localhost:8080/ || exit 1
